name: Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print the text
        run: |
          echo "Hello world"
          # Add your deployment steps here
